[package]
name = "ddos"
version = "0.1.0"
authors = ["Katharina Fey <kookie@spacekookie.de>"]

[dependencies]
toml = "0.4"
serde_derive = "1.0"
clap = "2.26.2"
serde = "1.0"
gpgme = "0.6.1"
colored = "1.5"